# @see https://docs.github.com/en/actions
# @see https://github.com/marketplace?verification=verified_creator&type=actions
jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull repository."
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Build Docker image."
        run: |
          chmod u+x --recursive src/main/bash
          docker build -t mipasm-compiler -f src/main/docker/compiler/Dockerfile .
      - name: "Build."
        run: |
          docker run --rm -v "$PWD:/project" -w /project mipasm-compiler src/main/bash/build.sh
      - name: "Test."
        run: |
          docker run --rm -v "$PWD:/project" -w /project mipasm-compiler src/main/bash/test.sh

name: "CI"

# @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  pull_request:
    types:
      - closed
      - reopened
  push:
